# Generated by Django 5.1.2 on 2024-11-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lanaguage',
            new_name='language',
        ),
    ]
