# Generated by Django 5.1.2 on 2024-10-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_ategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ategory',
            new_name='category',
        ),
    ]
