# Generated by Django 4.1.3 on 2022-12-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_room_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="ameities",
            new_name="amenities",
        ),
    ]
